export const copy = {
  brand: {
    name: 'Atelier Six',
  },
  nav: {
    today: 'Today',
    learn: 'Learn',
    practise: 'Practise',
    tuner: 'Tuner',
    you: 'You',
    search: '⌘K Search',
  },
  learn: {
    course: 'Course',
    chords: 'Chords',
  },
  you: {
    progress: 'Progress',
    settings: 'Settings',
  },
  today: {
    title: 'Today',
  },
  onboarding: {
    title: 'Welcome to the atelier',
    welcomeBody: 'A calm, focused way to learn guitar.',
    handTitle: 'Which hand do you play with',
    handLeft: 'Left-handed',
    handRight: 'Right-handed',
    levelTitle: 'Your level',
    levelNew: 'New to guitar',
    levelSomeChords: 'I know some chords',
    levelConfident: 'Confident with chords',
    tuningTitle: 'Tuning and capo',
    next: 'Next',
    back: 'Back',
    skip: 'Skip',
    done: 'Start',
    stepLabel: 'Step {current} of {total}',
    restart: 'Redo onboarding',
  },
  course: {
    title: 'Course',
    learnTitle: 'Learn',
    intro:
      'Five styles, one idea: chords are easy, changes are hard. Each module orders its lessons from the gentlest change to the most demanding.',
    finishLabel: '{finish} finish',
    lessonCount: '{count} lessons',
    statusNew: 'New',
    statusProgress: '{done} of {total}',
    comingSoon: 'Coming in v1.1',
    moduleCrumb: 'Learn · Module {number} · {finish} finish',
    moduleSubtitle: '{style} · listening references: {artists}',
    lessonsHeading: 'Lessons · gentlest change first',
    complete: '{done} of {total} complete',
    progressRing: '{done} of {total} lessons complete',
    continue: 'Continue: {title}',
    start: 'Start',
    startLesson: 'Start {title}',
    toneRecipe: 'Tone recipe',
    listenFor: 'Listen for',
    listenNote: 'Named as listening references only. No song tabs.',
    skills: 'Skills',
    notFound: 'That module does not exist.',
    backToCourse: 'Back to the course',
    finishes: {
      nitro: 'Nitro',
      xerox: 'Xerox',
      sunburst: 'Sunburst',
      faded: 'Faded',
      stencil: 'Stencil',
    },
    modules: {
      power: {
        title: 'Power chords',
        style: 'Pop punk',
        tone: 'Gain 7 · Bass 6 · Mid 4 · Treble 6',
        toneNote: 'Bridge humbucker, palm-muted verse, open chorus.',
        skill1: 'Locked shapes',
        skill2: 'Downpicking',
        skill3: 'Palm muting',
        skill4: 'Octaves',
      },
      open: {
        title: 'Open chords',
        style: 'Britpop',
        tone: 'Clean · Bass 5 · Mid 6 · Treble 7',
        toneNote: 'Acoustic or clean electric, capo on, let the top strings ring.',
        skill1: 'Anchor fingers',
        skill2: 'Sixteenth strum',
        skill3: 'Capo',
        skill4: 'Ringing top strings',
      },
      lead: {
        title: 'Lead',
        style: 'Grunge-melodic lead',
        tone: '',
        toneNote: '',
        skill1: 'Bends',
        skill2: 'Slides',
        skill3: 'Vibrato',
        skill4: 'Melodic solos',
      },
      thumb: {
        title: 'Thumb-over',
        style: 'Thumb-over funk',
        tone: '',
        toneNote: '',
        skill1: 'Thumb-over triads',
        skill2: 'Ghost notes',
        skill3: 'Hammer-ons',
        skill4: 'Muted scratches',
      },
      whammy: {
        title: 'Whammy',
        style: 'Rap-rock Whammy',
        tone: '',
        toneNote: '',
        skill1: 'Drop D',
        skill2: 'Killswitch',
        skill3: 'Pedal',
        skill4: 'Call and response',
      },
    },
  },
  library: {
    title: 'Chord library',
    modulePower: 'Power (pop punk)',
    moduleOpen: 'Open (Britpop)',
    moduleThumb: 'Thumb-over',
    moduleLead: 'Lead',
    moduleWhammy: 'Whammy',
    comingSoon: '{label} · Coming in v1.1',
    searchLabel: 'Search chords',
    searchPlaceholder: 'Search by chord name…',
    registerLabel: 'Register',
    registerAll: 'All',
    registerLow: 'Low',
    registerMid: 'Mid',
    registerHigh: 'High',
    tagLabel: 'Shape',
    tagAll: 'All',
    tagBarre: 'Barre',
    tagAnchored: 'Anchored',
    noResults: 'No chords match those filters.',
    shapeCount: '{count} shapes',
    compareLabel: 'Compare transition',
    comparePlaceholder: 'Choose a chord…',
    hearChord: 'Hear chord',
  },
  lesson: {
    title: 'Lesson',
    keepFingers: 'Keep finger {fingers} where it is.',
    demoTitle: 'C–G–Am–F practice loop',
    play: 'Play',
    stop: 'Stop',
    crumb: 'Learn · {module} · Lesson {number}',
    notFound: 'That lesson does not exist.',
    section: 'Section',
    sectionNames: {
      intro: 'Intro',
      verse: 'Verse',
      pre: 'Pre-chorus',
      chorus: 'Chorus',
      bridge: 'Bridge',
      breakdown: 'Breakdown',
    },
    difficulty: '{label} · {score}',
    difficultyLabels: {
      gentle: 'Gentle',
      moderate: 'Moderate',
      demanding: 'Demanding',
    },
    tabHeading: 'Tab · {section}',
    now: 'Now',
    next: 'Next',
    theChange: 'The change',
    sameChord: 'One chord all the way: keep the hand relaxed and the arm moving.',
    layers: 'Layers',
    layerRoles: {
      rhythm: 'Rhythm',
      double: 'Double',
      contrast: 'Contrast',
      riff: 'Riff',
    },
    mute: 'Mute {layer}',
    solo: 'Solo {layer}',
    loop: 'Loop',
    tempo: 'Tempo (bpm)',
    metronome: 'Metronome',
    countIn: 'Count-in',
    copyTab: 'Copy tab',
    copied: 'Tab copied',
    tips: 'Tips',
    listenFor: 'Listen for',
    rotateHint: 'Turn your phone sideways to see the tab.',
    listenRef: '{artist} · {song}',
    barOf: 'Bar {bar} of {total}',
    tuningNames: {
      standard: 'Standard',
      halfDown: 'Half-step down',
      dropD: 'Drop D',
    },
  },
  metronome: {
    start: 'Start metronome',
    stop: 'Stop metronome',
    bpmLabel: 'Tempo (bpm)',
    tap: 'Tap tempo',
    countInLabel: 'Count-in bars',
  },
  miniPlayer: {
    stop: 'Stop',
    next: 'Next: {chord}',
    bpm: '{bpm} bpm',
  },
  practiseScreen: {
    title: 'Practise',
  },
  drills: {
    title: 'Drills',
    intro: 'Pick any two chords and drill the change between them.',
    from: 'From chord',
    to: 'To chord',
    kind: 'Drill',
    kinds: {
      loop: 'Two-chord loop',
      early: 'Early change',
      freeze: 'Freeze and check',
      minute: 'One minute',
    },
    hints: {
      loop: 'Two bars each, round and round. Keep the strumming steady.',
      early: 'Start moving on beat 4: the target lights up when it is time.',
      freeze: 'Playback pauses on each new chord so you can check every finger.',
      minute: 'Count clean changes in 60 seconds. Tap Change or press Space.',
    },
    tempo: 'Tempo (bpm)',
    freezeSeconds: 'Freeze (seconds)',
    changeNow: 'Change now',
    frozen: 'Check your fingers',
    start: 'Start the minute',
    change: 'Change',
    changes: '{count} changes',
    secondsLeft: '{seconds} s',
    timeLeft: 'Time left',
    finished: 'Time! {count} clean changes.',
    again: 'Go again',
    best: 'Best: {count}',
    history: 'Recent minutes',
    historyEntry: '{from} → {to}: {count}',
    drillThis: 'Drill this change',
    playerTitle: '{from} ↔ {to} drill',
  },
  tunerScreen: {
    title: 'Tuner',
  },
  progressScreen: {
    title: 'Progress',
  },
  settings: {
    title: 'Settings',
    mode: 'Appearance',
    modeDark: 'Dark',
    modeLight: 'Light',
    modeSystem: 'System',
    finish: 'Finish',
    motion: 'Motion',
    motionOn: 'On',
    motionOff: 'Off',
    motionSystem: 'System',
    sound: 'Sound',
    leftHanded: 'Left-handed',
    tuning: 'Tuning',
    tuningStandard: 'Standard',
    tuningHalfDown: 'Half-step down',
    tuningDropD: 'Drop D',
    capo: 'Capo',
    robotMode: 'Robot mode',
    robotModeHint: 'Perfectly on the grid — useful for timing practice.',
    downloadSounds: 'Download sounds for offline',
    downloadingSounds: 'Downloading…',
    soundsDownloaded: 'Sounds are ready offline',
  },
  design: {
    title: 'Design',
    colours: 'Colours',
    typeScale: 'Type scale',
    spacing: 'Spacing',
    components: 'Components',
    logo: 'Logo',
    finish: 'Finish',
    mode: 'Mode',
    motion: 'Motion',
    buttons: 'Buttons',
    loading: 'Loading',
    panels: 'Panels',
    dividers: 'Dividers',
    headings: 'Headings',
    text: 'Text',
    pills: 'Pills',
    slider: 'Slider',
    toggle: 'Toggle',
    segmented: 'Segmented control',
    dial: 'Dial',
    sheet: 'Sheet',
    openSheet: 'Open sheet',
    sheetDemo: 'Sheet demo',
    sheetBody: 'This is a bottom sheet on mobile and a side panel from 640px up.',
    typeSample: 'Aa',
    fretboard: 'Fretboard',
    transitionCard: 'Transition card',
    tabLane: 'Tab lane',
    audio: 'Audio',
    strummedChord: 'Strummed chord',
    palmMutedRiff: 'Palm-muted riff',
    drumGroove: 'Drum groove',
  },
  transition: {
    keepOne: 'Keep finger {finger} where it is.',
    keepMany: 'Keep fingers {fingers} where they are.',
    lift: 'Lift finger {finger} to the {string} string, {fret} fret.',
    place: 'Place finger {finger} on the {string} string, {fret} fret.',
    release: 'Release finger {finger} from the {string} string.',
    slideOne: 'Slide fingers {fingers} together 1 fret towards the {direction}.',
    slideMany: 'Slide fingers {fingers} together {frets} frets towards the {direction}.',
    shiftOne: 'Move fingers {fingers} together across 1 string, towards the {thickness} strings.',
    shiftMany:
      'Move fingers {fingers} together across {strings} strings, towards the {thickness} strings.',
    bridge: 'bridge',
    headstock: 'headstock',
    thinner: 'thinner',
    thicker: 'thicker',
    difficultyGentle: 'Gentle',
    difficultyModerate: 'Moderate',
    difficultyDemanding: 'Demanding',
    overlayAnchor: 'Finger {finger} stays anchored.',
    overlayGuide: 'Finger {finger} guides to the {string} string, {fret} fret.',
    overlayLift: 'Finger {finger} lifts to the {string} string, {fret} fret.',
    overlayPlace: 'Finger {finger} places on the {string} string, {fret} fret.',
    overlayRelease: 'Finger {finger} releases.',
    overlayShiftGroup: 'Fingers {fingers} shift together.',
    overlaySlideGroup: 'Fingers {fingers} slide together.',
  },
  tabLane: {
    palmMute: 'P.M.',
    down: '↓',
    up: '↑',
    accent: '>',
    ghostWrap: '({value})',
    header: '{tempo} bpm · {tuning} · capo {capo} · {key}',
    repeatEnd: ':||',
    dynamicPiano: 'p',
    dynamicMezzoForte: 'mf',
    dynamicForte: 'f',
  },
  fretboard: {
    barre: '{finger} finger barre {fromString} to {toString} string fret {fret}',
    fingerFret: '{finger} finger {string} string fret {fret}',
    openOne: '{strings} string open',
    openMany: '{strings} strings open',
    mutedOne: '{strings} string muted',
    mutedMany: '{strings} strings muted',
    and: 'and',
    thumb: 'thumb',
    startFret: '{fret}fr',
    mutedSymbol: '×',
    openSymbol: '○',
  },
  skipToContent: 'Skip to content',
  close: 'Close',
  commandPalette: {
    title: 'Command palette',
    placeholder: 'Search lessons, chords, drills, settings…',
    noResults: 'No matches',
    recent: 'Recent',
    startTuner: 'Start tuner',
    search: 'Search',
  },
};

type Copy = typeof copy;

type Path<T> = T extends string
  ? never
  : {
      [K in keyof T]: T[K] extends string ? K : `${K & string}.${Path<T[K]> & string}`;
    }[keyof T];

function resolve(source: unknown, path: string): unknown {
  return path.split('.').reduce<unknown>((acc, key) => {
    if (acc && typeof acc === 'object' && key in acc) {
      return (acc as Record<string, unknown>)[key];
    }
    return undefined;
  }, source);
}

export function t(path: Path<Copy>, vars?: Record<string, string | number>): string {
  const value = resolve(copy, path);
  if (typeof value !== 'string') {
    throw new Error(`Missing copy for "${path}"`);
  }
  if (!vars) return value;
  return value.replace(/\{(\w+)\}/g, (match, key: string) => {
    const replacement = vars[key];
    return replacement === undefined ? match : String(replacement);
  });
}
