export const copy = {
  brand: {
    name: 'Atelier Six',
  },
  nav: {
    today: 'Today',
    learn: 'Learn',
    practise: 'Practise',
    tuner: 'Tuner',
    you: 'You',
    search: '⌘K Search',
    crumbSeparator: ' · ',
  },
  learn: {
    course: 'Course',
    chords: 'Chords',
  },
  you: {
    progress: 'Progress',
    settings: 'Settings',
    tabs: 'You',
  },
  today: {
    title: 'Today',
    intro: 'Three short steps. Take them in order, or pick one.',
    ring: 'Practice today: {minutes} of {goal} minutes',
    ringValue: '{minutes} / {goal} min',
    warmup: 'Warm-up',
    warmupDetail: 'Fingers {pattern} from fret {fret}, one finger per fret, at {bpm} bpm.',
    warmupTab: 'Warm-up tab',
    start: 'Start',
    stop: 'Stop',
    startClick: 'Start the click',
    stopClick: 'Stop the click',
    newLesson: 'New lesson',
    tune: 'Play time',
    tuneReady: 'Your module tune is ready: {title}.',
    playRiff: 'Riff of the week: {title}.',
    playJam: 'Jam over a two-chord loop at your own pace.',
    startPlay: 'Start play time',
    minutes: '{minutes} min',
    allDone: 'Every lesson is done. Pick any one to polish.',
    browse: 'Browse the course',
    reviews: 'Reviews',
    reviewsHint: 'Changes due again, the ones you miss most first.',
    reviewsEmpty: 'Nothing due today.',
    reviewEntry: '{from} → {to}',
    drill: 'Drill',
    drillLabel: 'Drill {from} to {to}',
  },
  onboarding: {
    title: 'Welcome to the atelier',
    titleShort: 'Welcome',
    welcomeBody: 'A calm, focused way to learn guitar.',
    handTitle: 'Which hand do you play with',
    handLeft: 'Left-handed',
    handRight: 'Right-handed',
    levelTitle: 'Your level',
    levelNew: 'New to guitar',
    levelSomeChords: 'I know some chords',
    levelConfident: 'Confident with chords',
    tuningTitle: 'Tuning and capo',
    next: 'Next',
    back: 'Back',
    skip: 'Skip',
    done: 'Start',
    stepLabel: 'Step {current} of {total}',
    restart: 'Redo onboarding',
    grooveTitle: 'Your first groove',
    grooveBody:
      'Play along with the band: {a} and {b}, one bar each, round and round. No drills yet, just music.',
    playGroove: 'Play the groove',
    stopGroove: 'Stop the groove',
  },
  course: {
    title: 'Course',
    learnTitle: 'Learn',
    intro:
      'Five styles, one idea: chords are easy, changes are hard. Each module orders its lessons from the gentlest change to the most demanding.',
    finishLabel: '{finish} finish',
    lessonCount: '{count} lessons',
    statusNew: 'New',
    statusStarted: 'Started',
    statusNotYet: 'Not yet',
    bestTempo: 'Best {bpm} bpm',
    doneBest: 'Done · best {bpm} bpm',
    doneLabel: 'Done',
    theTune: 'The tune',
    tuneHint: 'An original piece in the style, with the band. The payoff for this module.',
    playTune: 'Play the tune',
    riffs: 'Riffs of the week',
    riffLocked: 'Unlocks after lesson {number}.',
    riffBars: '{bars} bars',
    riffTab: '{title} tab',
    playRiff: 'Play {title}',
    stopRiff: 'Stop {title}',
    statusProgress: '{done} of {total}',
    comingSoon: 'Coming in v1.1',
    moduleCrumb: 'Module {number} · {finish} finish',
    lessonsHeading: 'Lessons · gentlest change first',
    complete: '{done} of {total} complete',
    progressRing: '{done} of {total} lessons complete',
    continue: 'Continue: {title}',
    start: 'Start',
    startLesson: 'Start {title}',
    toneRecipe: 'Tone recipe',
    skills: 'Skills',
    notFound: 'That module does not exist.',
    backToCourse: 'Back to the course',
    prevModule: '← {title}',
    nextModule: '{title} →',
    moduleNav: 'Module navigation',
    finishes: {
      nitro: 'Nitro',
      xerox: 'Xerox',
      sunburst: 'Sunburst',
      faded: 'Faded',
      stencil: 'Stencil',
    },
    modules: {
      power: {
        title: 'Power chords',
        style: 'Pop punk',
        tone: 'Gain 7 · Bass 6 · Mid 4 · Treble 6',
        toneNote: 'Bridge humbucker, palm-muted verse, open chorus.',
        skill1: 'Locked shapes',
        skill2: 'Downpicking',
        skill3: 'Palm muting',
        skill4: 'Octaves',
      },
      open: {
        title: 'Open chords',
        style: 'Britpop',
        tone: 'Clean · Bass 5 · Mid 6 · Treble 7',
        toneNote: 'Acoustic or clean electric, capo on, let the top strings ring.',
        skill1: 'Anchor fingers',
        skill2: 'Sixteenth strum',
        skill3: 'Capo',
        skill4: 'Ringing top strings',
      },
      lead: {
        title: 'Lead',
        style: 'Grunge-melodic lead',
        tone: '',
        toneNote: '',
        skill1: 'Bends',
        skill2: 'Slides',
        skill3: 'Vibrato',
        skill4: 'Melodic solos',
      },
      thumb: {
        title: 'Thumb-over',
        style: 'Thumb-over funk',
        tone: '',
        toneNote: '',
        skill1: 'Thumb-over triads',
        skill2: 'Ghost notes',
        skill3: 'Hammer-ons',
        skill4: 'Muted scratches',
      },
      whammy: {
        title: 'Whammy',
        style: 'Rap-rock Whammy',
        tone: '',
        toneNote: '',
        skill1: 'Drop D',
        skill2: 'Killswitch',
        skill3: 'Pedal',
        skill4: 'Call and response',
      },
    },
  },
  library: {
    title: 'Chord library',
    modulePower: 'Power (pop punk)',
    moduleOpen: 'Open (Britpop)',
    moduleThumb: 'Thumb-over',
    moduleLead: 'Lead',
    moduleWhammy: 'Whammy',
    comingSoon: '{label} · Coming in v1.1',
    searchLabel: 'Search chords',
    searchPlaceholder: 'Search by chord name…',
    registerLabel: 'Register',
    registerAll: 'All',
    registerLow: 'Low',
    registerMid: 'Mid',
    registerHigh: 'High',
    tagLabel: 'Shape',
    tagAll: 'All',
    tagBarre: 'Barre',
    tagAnchored: 'Anchored',
    noResults: 'No chords match those filters.',
    shapeCount: '{count} shapes',
    compareLabel: 'Compare transition',
    comparePlaceholder: 'Choose a chord…',
    hearChord: 'Hear chord',
  },
  lesson: {
    title: 'Lesson',
    keepFingers: 'Keep finger {fingers} where it is.',
    demoTitle: 'C–G–Am–F practice loop',
    play: 'Play',
    stop: 'Stop',
    crumbLesson: 'Lesson {number}',
    notFound: 'That lesson does not exist.',
    section: 'Section',
    sectionNames: {
      intro: 'Intro',
      verse: 'Verse',
      pre: 'Pre-chorus',
      chorus: 'Chorus',
      bridge: 'Bridge',
      breakdown: 'Breakdown',
    },
    difficulty: '{label} · {score}',
    difficultyLabels: {
      gentle: 'Gentle',
      moderate: 'Moderate',
      demanding: 'Demanding',
    },
    tabHeading: 'Tab · {section}',
    now: 'Now',
    next: 'Next',
    soundsAs: '{shape} shape — sounds {sounding}',
    theChange: 'The change',
    sameChord: 'One chord all the way: keep the hand relaxed and the arm moving.',
    layers: 'Layers',
    layerRoles: {
      rhythm: 'Rhythm',
      double: 'Double',
      contrast: 'Contrast',
      riff: 'Riff',
    },
    mute: 'Mute {layer}',
    solo: 'Solo {layer}',
    loop: 'Loop',
    tempo: 'Tempo (bpm)',
    tempoValue: '{bpm} bpm',
    tempoSlower: 'Slower',
    tempoFaster: 'Faster',
    metronome: 'Metronome',
    countIn: 'Count-in',
    listen: 'Listen',
    tips: 'Tips',
    rotateHint: 'Turn your phone sideways to see the tab.',
    barOf: 'Bar {bar} of {total}',
    mode: 'Mode',
    modes: {
      perform: 'Performance',
      practise: 'Practise a section',
    },
    crumbTune: 'The tune',
    markComplete: 'Mark complete',
    completed: 'Completed',
    completedHint: 'Shows up as done across the course and your progress.',
    markCompleteHint: 'Done with this one? Mark it complete to move on.',
    finishTitle: 'Nicely played.',
    finishBody: 'That was the whole tune, start to finish.',
    playAgain: 'Play it again',
    backToModule: 'Back to the module',
    prevLesson: '← {title}',
    nextLesson: '{title} →',
    prevModule: '← Previous module: {title}',
    nextModule: 'Next module: {title} →',
    pager: 'Lesson navigation',
    tuningNames: {
      standard: 'Standard',
      halfDown: 'Half-step down',
      dropD: 'Drop D',
    },
  },
  foundations: {
    title: 'Foundations',
    style: 'Start here',
    intro:
      'Five short, hands-on lessons before the chords: reading tab, holding the guitar, tuning, clean notes and a hand warm-up.',
    optional: 'Optional for you',
    lessonCount: '{count} lessons',
    minutes: '{minutes} min',
    crumb: 'Learn · Foundations · {number} of {total}',
    back: 'All foundations',
    next: 'Next lesson',
    start: 'Start',
    done: 'Done',
    lessons: {
      'read-tab': {
        title: 'How to read tab',
        goal: 'Tap each number to see where it sits on the neck, then read a short line on your own.',
      },
      hold: {
        title: 'Holding the guitar and the pick',
        goal: 'Get comfortable before you play: posture, pick grip and where the picking hand rests.',
      },
      'tune-up': {
        title: 'Your first tune-up',
        goal: 'Go string by string, low to high, until every string matches its note.',
      },
      fretting: {
        title: 'Fretting cleanly',
        goal: 'Make each note ring: finger just behind the fret, thumb relaxed behind the neck.',
      },
      'hand-health': {
        title: 'Hand-health warm-up',
        goal: 'Two minutes of gentle movement to get your hands ready.',
      },
    },
    tab: {
      lines:
        'Six lines are the six strings. The top line is the thinnest string, high e; the bottom is the thickest, low E.',
      numbers: 'A number is the fret to press. 0 means play the string open, with no finger.',
      counts:
        'The row underneath is the count. Say "1 and 2 and…" and play each note on its count.',
      muted:
        'An x is a muted note: rest your fretting fingers on the string and strike it for a click.',
      palmMute:
        'P.M. means palm mute: rest the side of your picking hand on the strings by the bridge.',
      picking: '↓ is a downstroke, ↑ an upstroke.',
      symbol: 'Symbol {current} of {total}',
      nextSymbol: 'Next symbol',
      exercise: 'Tap a note',
      noteLabel: 'Note {n}: {string} string, fret {fret}',
      nowPlaying: '{string} string, fret {fret}',
      check: 'Read and play',
      checkIntro: 'Thirty seconds: read the line and answer three questions.',
      checkStart: 'Start the check',
      question: 'Which fret is note {n} on?',
      fretOption: 'Fret {fret}',
      score: '{correct} of {total} right.',
      secondsLeft: '{seconds} s left',
      timeUp: 'Time is up. {correct} of {total} right.',
    },
    hold: {
      sitting:
        'Sitting: guitar body on your right leg (left leg if you play left-handed), back straight, neck angled slightly up.',
      standing: 'Standing: strap set so the guitar sits at the same height as when you sit.',
      pick: 'Pick grip: hold the pick between the pad of your thumb and the side of your first finger, with just the tip showing.',
      palm: 'Palm rest: for palm muting, the side of your picking hand rests lightly on the strings right by the bridge.',
      sittingLabel: 'A player sitting with the guitar on one leg',
      pickLabel: 'A pick held between thumb and first finger',
      palmLabel: 'The side of the hand resting on the strings by the bridge',
    },
    tune: {
      intro:
        'Tune one string at a time, from the thickest to the thinnest. Play the reference note, then turn the peg until your string matches.',
      sharp: 'Sharp means too high: loosen the string a little.',
      flat: 'Flat means too low: tighten it a little. Tuning up to the note is steadier than tuning down.',
      string: '{name} string · {note} · {hz} Hz',
      play: 'Play {note}',
      tuner: 'Open the tuner',
    },
    fret: {
      tips1: 'Press just behind the fret wire, not on top of it or halfway back.',
      tips2: 'Keep your thumb relaxed behind the neck, roughly behind your second finger.',
      tips3:
        'Buzzing usually means too far from the fret or not quite enough pressure; a dull thud means another finger is touching the string.',
      check: 'Play the 3rd fret on each string and tell the app how it sounded.',
      prompt: '{string} string, 3rd fret',
      clean: 'Rang clearly',
      buzzed: 'Buzzed or muffled',
      allClean: 'Every string rang clearly. Nicely done.',
      muffled:
        'Muffled: {strings}. Move a little closer to the fret on those strings and try again.',
      again: 'Try again',
    },
    health: {
      intro: 'Two minutes of gentle movement. Go slowly and stay within what feels easy.',
      stop: 'Stop if anything hurts. If pain carries on after you stop playing, see a doctor or physiotherapist.',
      start: 'Start the warm-up',
      pause: 'Pause',
      resume: 'Resume',
      timer: 'Warm-up time left',
      left: '{seconds} s',
      finished: 'All done. Your hands are ready.',
      movements: {
        shake: 'Let your arms hang and shake your hands loosely.',
        fists: 'Make a soft fist, then open your hand wide. Slowly, ten times.',
        spread: 'Spread your fingers apart, then bring them together.',
        thumbs: 'Touch your thumb to each fingertip in turn, both hands.',
        wrists: 'Circle your wrists gently, five times each way.',
        breathe: 'Drop your shoulders, breathe out, and rest your hands.',
      },
    },
    offer: 'This one is demanding on the hands. Warm up for two minutes first?',
    offerLong: 'You have played for over half an hour today. A two-minute hand warm-up?',
    offerGo: 'Do the warm-up',
    offerSkip: 'Skip for today',
  },
  practice: {
    feedback: 'How was that loop?',
    clean: 'Clean',
    missed: 'Missed',
    cleanKey: 'C',
    missedKey: 'M',
    rate: '{percent} % clean',
    targetReached: 'Target reached',
    easier: 'Easier part on',
  },
  shortcuts: {
    title: 'Keyboard shortcuts',
    open: 'Shortcuts',
    listeningForCommands: 'Listening for commands',
    togglePlay: 'Play / stop',
    next: 'Next',
    prev: 'Previous',
    toggleLoop: 'Toggle loop',
    slower: 'Slower',
    faster: 'Faster',
    clean: 'Mark clean',
    missed: 'Mark missed',
    tuner: 'Open tuner',
    help: 'Show this list',
    keyTogglePlay: 'Space',
    keyNext: '→ / Page Down',
    keyPrev: '← / Page Up',
    keyToggleLoop: 'L',
    keySlower: '-',
    keyFaster: '+',
    keyClean: 'C',
    keyMissed: 'M',
    keyTuner: 'T',
    keyHelp: '?',
  },
  metronome: {
    start: 'Start metronome',
    stop: 'Stop metronome',
    bpmLabel: 'Tempo (bpm)',
    tap: 'Tap tempo',
    countInLabel: 'Count-in bars',
  },
  miniPlayer: {
    stop: 'Stop',
    next: 'Next: {chord}',
    bpm: '{bpm} bpm',
  },
  practiseScreen: {
    title: 'Practise',
  },
  drills: {
    title: 'Drills',
    intro: 'Pick any two chords and drill the change between them.',
    from: 'From chord',
    to: 'To chord',
    kind: 'Drill',
    kinds: {
      loop: 'Two-chord loop',
      early: 'Early change',
      freeze: 'Freeze and check',
      minute: 'One minute',
    },
    hints: {
      loop: 'Two bars each, round and round. Keep the strumming steady.',
      early: 'Start moving on beat 4: the target lights up when it is time.',
      freeze: 'Playback pauses on each new chord so you can check every finger.',
      minute: 'Count clean changes in 60 seconds. Tap Change or press Space.',
    },
    tempo: 'Tempo (bpm)',
    freezeSeconds: 'Freeze (seconds)',
    changeNow: 'Change now',
    frozen: 'Check your fingers',
    start: 'Start the minute',
    change: 'Change',
    changes: '{count} changes',
    secondsLeft: '{seconds} s',
    timeLeft: 'Time left',
    finished: 'Time! {count} clean changes.',
    again: 'Go again',
    best: 'Best: {count}',
    history: 'Recent minutes',
    historyEntry: '{from} → {to}: {count}',
    drillThis: 'Drill this change',
    playerTitle: '{from} ↔ {to} drill',
  },
  tunerScreen: {
    title: 'Tuner',
    start: 'Start',
    stop: 'Stop',
    statusIdle: 'Stopped',
    statusStarting: 'Starting…',
    statusListening: 'Listening',
    statusStopped: 'Stopped',
    statusDenied: 'Microphone access was denied. Allow it in your browser settings to tune by ear.',
    statusUnsupported: "This browser can't access the microphone, so auto-detect isn't available.",
    inTune: 'In tune',
    listenForNote: 'Play a string to see its name here.',
    referenceToneLabel: 'Play {note} reference tone',
    inputLevel: 'mic {level} · freq {freq}Hz · clarity {clarity}',
    tuning: 'Tuning',
    a4Label: 'A4 calibration',
  },
  progressScreen: {
    title: 'Progress',
    week: '{minutes} minutes this week',
    today: 'Today',
    todayValue: '{minutes} / {goal} min',
    todayLabel: 'Practice today: {minutes} of {goal} minutes',
    modules: 'Modules',
    lessonsDone: '{done} of {total} lessons',
    shortNames: {
      power: 'Power',
      open: 'Open',
      lead: 'Lead',
      thumb: 'Thumb',
      whammy: 'Whammy',
    },
    moduleState: '{done}/{total}',
    changes: 'Chord changes',
    changesCaption:
      'How often each change is missed. Rows are the chord you leave, columns the one you land on.',
    changesEmpty: 'Play a lesson or a drill and mark Clean or Missed to fill this in.',
    cellLabel: '{from} to {to}: {percent} % missed',
    cellEmpty: '{from} to {to}: not practised yet',
    cellSame: '{from}: same chord',
    percent: '{percent}%',
    fewer: 'Fewer',
    more: 'More',
    drillWorst: 'Drill {from} → {to}',
    worstFirst: 'Worst first',
    worstEntry: '{from} → {to}',
    missed: '{percent}% missed',
    drillThis: 'Drill this',
    minutes: 'One-minute changes',
    minuteBest: 'Best {count}',
    minutesEmpty: 'No one-minute scores yet.',
    lessons: '{module} · best tempo',
    noTempo: '—',
    tempo: '{bpm} bpm',
  },
  settings: {
    title: 'Settings',
    mode: 'Appearance',
    modeDark: 'Dark',
    modeLight: 'Light',
    modeSystem: 'System',
    finish: 'Finish',
    finishNitro: 'Nitro',
    finishXerox: 'Xerox',
    finishSunburst: 'Sunburst',
    finishFaded: 'Faded',
    finishStencil: 'Stencil',
    pinnedFinish: 'Pin this finish',
    pinnedFinishHint:
      'Lessons choose their own finish; turn this on to keep the one above instead.',
    motion: 'Motion',
    motionOn: 'On',
    motionOff: 'Off',
    motionSystem: 'System',
    sound: 'Sound',
    leftHanded: 'Left-handed',
    tuning: 'Tuning',
    tuningStandard: 'Standard',
    tuningHalfDown: 'Half-step down',
    tuningDropD: 'Drop D',
    capo: 'Capo',
    robotMode: 'Robot mode',
    robotModeHint: 'Perfectly on the grid — useful for timing practice.',
    downloadSounds: 'Download sounds for offline',
    downloadingSounds: 'Downloading…',
    soundsDownloaded: 'Sounds are ready offline',
    progress: 'Your progress',
    progressHint: 'Move your progress to another device without an account.',
    exportProgress: 'Export progress',
    importProgress: 'Import progress',
    importDone: 'Progress imported.',
    importFailed: 'That file is not Atelier Six progress.',
    footPedalTest: 'Foot pedal test',
    footPedalTestHint: 'Press a pedal button or key to see which action it sends.',
    footPedalTestWaiting: 'Waiting for a key…',
    voiceCommands: 'Voice commands',
    voiceCommandsHint:
      'Say "play", "stop", "slower", "faster", "loop", "next", "back" or "tempo 90". Some browsers send what you say to a cloud speech service to understand it.',
    install: 'Install Atelier Six',
    installHint: 'Add it to your home screen for a full-screen, offline-ready app.',
    installAction: 'Install',
    installed: 'Installed',
    installIosHint: 'In Safari, tap Share, then "Add to Home Screen".',
  },
  pwa: {
    updateAvailable: 'Update available',
    reload: 'Reload',
    offlineReady: 'Ready to work offline',
  },
  design: {
    title: 'Design',
    colours: 'Colours',
    typeScale: 'Type scale',
    spacing: 'Spacing',
    components: 'Components',
    logo: 'Logo',
    finish: 'Finish',
    mode: 'Mode',
    motion: 'Motion',
    buttons: 'Buttons',
    loading: 'Loading',
    panels: 'Panels',
    dividers: 'Dividers',
    headings: 'Headings',
    text: 'Text',
    pills: 'Pills',
    slider: 'Slider',
    toggle: 'Toggle',
    segmented: 'Segmented control',
    dial: 'Dial',
    sheet: 'Sheet',
    openSheet: 'Open sheet',
    sheetDemo: 'Sheet demo',
    sheetBody: 'This is a bottom sheet on mobile and a side panel from 640px up.',
    typeSample: 'Aa',
    fretboard: 'Fretboard',
    transitionCard: 'Transition card',
    tabLane: 'Tab lane',
    audio: 'Audio',
    strummedChord: 'Strummed chord',
    palmMutedRiff: 'Palm-muted riff',
    drumGroove: 'Drum groove',
  },
  transition: {
    keepOne: 'Keep finger {finger} where it is.',
    keepMany: 'Keep fingers {fingers} where they are.',
    lift: 'Lift finger {finger} to the {string} string, {fret} fret.',
    place: 'Place finger {finger} on the {string} string, {fret} fret.',
    release: 'Release finger {finger} from the {string} string.',
    slideOne: 'Slide fingers {fingers} together 1 fret towards the {direction}.',
    slideMany: 'Slide fingers {fingers} together {frets} frets towards the {direction}.',
    shiftOne: 'Move fingers {fingers} together across 1 string, towards the {thickness} strings.',
    shiftMany:
      'Move fingers {fingers} together across {strings} strings, towards the {thickness} strings.',
    bridge: 'bridge',
    headstock: 'headstock',
    thinner: 'thinner',
    thicker: 'thicker',
    difficultyGentle: 'Gentle',
    difficultyModerate: 'Moderate',
    difficultyDemanding: 'Demanding',
    overlayAnchor: 'Finger {finger} stays anchored.',
    overlayGuide: 'Finger {finger} guides to the {string} string, {fret} fret.',
    overlayLift: 'Finger {finger} lifts to the {string} string, {fret} fret.',
    overlayPlace: 'Finger {finger} places on the {string} string, {fret} fret.',
    overlayRelease: 'Finger {finger} releases.',
    overlayShiftGroup: 'Fingers {fingers} shift together.',
    overlaySlideGroup: 'Fingers {fingers} slide together.',
  },
  tabLane: {
    palmMute: 'P.M.',
    down: '↓',
    up: '↑',
    accent: '>',
    ghostWrap: '({value})',
    header: '{tempo} bpm · {tuning} · capo {capo} · {key}',
    repeatEnd: ':||',
    dynamicPiano: 'p',
    dynamicMezzoForte: 'mf',
    dynamicForte: 'f',
  },
  fretboard: {
    barre: '{finger} finger barre {fromString} to {toString} string fret {fret}',
    fingerFret: '{finger} finger {string} string fret {fret}',
    openOne: '{strings} string open',
    openMany: '{strings} strings open',
    mutedOne: '{strings} string muted',
    mutedMany: '{strings} strings muted',
    and: 'and',
    thumb: 'thumb',
    startFret: '{fret}fr',
    mutedSymbol: '×',
    openSymbol: '○',
  },
  skipToContent: 'Skip to content',
  close: 'Close',
  commandPalette: {
    title: 'Command palette',
    placeholder: 'Search lessons, chords, drills, settings…',
    noResults: 'No matches',
    recent: 'Recent',
    startTuner: 'Start tuner',
    search: 'Search',
  },
};

type Copy = typeof copy;

type Path<T> = T extends string
  ? never
  : {
      [K in keyof T]: T[K] extends string ? K : `${K & string}.${Path<T[K]> & string}`;
    }[keyof T];

function resolve(source: unknown, path: string): unknown {
  return path.split('.').reduce<unknown>((acc, key) => {
    if (acc && typeof acc === 'object' && key in acc) {
      return (acc as Record<string, unknown>)[key];
    }
    return undefined;
  }, source);
}

export function t(path: Path<Copy>, vars?: Record<string, string | number>): string {
  const value = resolve(copy, path);
  if (typeof value !== 'string') {
    throw new Error(`Missing copy for "${path}"`);
  }
  if (!vars) return value;
  return value.replace(/\{(\w+)\}/g, (match, key: string) => {
    const replacement = vars[key];
    return replacement === undefined ? match : String(replacement);
  });
}
